# Generated by Django 5.2a1 on 2025-02-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={"verbose_name": "Worker", "verbose_name_plural": "Workers"},
        ),
        migrations.RenameField(
            model_name="worker",
            old_name="team_lead",
            new_name="is_team_lead",
        ),
    ]
