# Generated by Django 5.2a1 on 2025-02-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0005_alter_task_project"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["deadline", "priority"]},
        ),
    ]
